# Generated by Django 5.2.8 on 2026-07-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingCelebration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom_name', models.CharField(max_length=120)),
                ('bride_name', models.CharField(max_length=120)),
                ('wedding_date', models.DateField()),
                ('ceremony_time', models.TimeField(blank=True, null=True)),
                ('church_name', models.CharField(default='Église', max_length=150)),
                ('priest_name', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Célébration de mariage',
                'verbose_name_plural': 'Célébrations de mariage',
                'ordering': ['wedding_date', 'ceremony_time'],
            },
        ),
    ]
