# Generated by Django 5.2.8 on 2026-07-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ma_celebration_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingcelebration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
